// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE6ujSVYd6yPSh48GYx_5XeLFBKUsw9Uo',
    appId: '1:495223274349:web:1d6d57f11fbedaee397864',
    messagingSenderId: '495223274349',
    projectId: 'flutter-agentic-app-4b55b',
    authDomain: 'flutter-agentic-app-4b55b.firebaseapp.com',
    storageBucket: 'flutter-agentic-app-4b55b.firebasestorage.app',
    measurementId: 'G-2G84RTW0CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANY7_QilZksZTsrw7o8hOYf05_U4sNIxc',
    appId: '1:495223274349:android:509ece8a8d842a55397864',
    messagingSenderId: '495223274349',
    projectId: 'flutter-agentic-app-4b55b',
    storageBucket: 'flutter-agentic-app-4b55b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HeVmyIWkcD9-AGtM6uEpdNwGTLya8Xw',
    appId: '1:495223274349:ios:e4929cc04ca787d0397864',
    messagingSenderId: '495223274349',
    projectId: 'flutter-agentic-app-4b55b',
    storageBucket: 'flutter-agentic-app-4b55b.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HeVmyIWkcD9-AGtM6uEpdNwGTLya8Xw',
    appId: '1:495223274349:ios:e4929cc04ca787d0397864',
    messagingSenderId: '495223274349',
    projectId: 'flutter-agentic-app-4b55b',
    storageBucket: 'flutter-agentic-app-4b55b.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE6ujSVYd6yPSh48GYx_5XeLFBKUsw9Uo',
    appId: '1:495223274349:web:9ecf5541f9060aea397864',
    messagingSenderId: '495223274349',
    projectId: 'flutter-agentic-app-4b55b',
    authDomain: 'flutter-agentic-app-4b55b.firebaseapp.com',
    storageBucket: 'flutter-agentic-app-4b55b.firebasestorage.app',
    measurementId: 'G-Z1JXBL9HQM',
  );
}
